section-engineering-education/engineering-education

authors/louise-findlay/index.md

I've added my updated bio from #65 in the new format

[Author Bio] Update Louise Findlay's Bio

---

articles/Getting-started-with-Pyspark-Spark-Part2/index.md

Hey @hectorkambow, I updated the article as suggested by the recent review. Let me know if it requires any more changes! :)

Getting started with Pyspark - Spark part2

---

articles/simple-guide-to-using-apis-nodejs/index.md

Corrected two links in my article, A Simple Guide to APIs because they point to the wrong article.

[Corrections] A Simple Guide to APIs

---

authors/nadiv-gold-edelstein/index.md

fixing a blank author page
Noticed this author page was blank (showed no articles)

fixing blank author page

---

.github/ISSUE_TEMPLATE/enged-content-idea-suggestion.md

Creating EngEd Content Idea Suggestion Template (using issues)

EngEd Content Idea Suggestions templates

---

.github/pull_request_template.md

creating PR template checklist for students to have before submitting a PR

creating PR template checklist

---

UPLOAD_INSTRUCTIONS.md

Updated upload instructions in line with article checklist.

Refined upload instructions

---

articles/performance-optimization-techniques-for-node-js/index.md

replacing replit links with standard code snippets

replacing replit links with standard code snippets

---

articles/javascript-dates-manipulation-with-date-fns/index.md

replacing links on dates article

replacing links on dates article

---

.github/ISSUE_TEMPLATE/enged-content-idea-suggestion.md
.github/ISSUE_TEMPLATE/how-to-guide-template.md

Adding How-To Guide Template 

---

.github/ISSUE_TEMPLATE/enged-content-idea-suggestion.md
.github/ISSUE_TEMPLATE/tutorials-format-template.md

adding tutorial template from docs

Tutorial Template

---

.github/ISSUE_TEMPLATE/enged-content-idea-suggestion.md
.github/ISSUE_TEMPLATE/software-review-template.md

adding software review template from docs

Software Review Template

---

articles/buffon-needle/index.md
articles/nodejs-date-and-time-objects-with-moment/index.md
articles/plagiarism-detection/index.md

replacing replit links with standard code blocks
for three articles

replacing replit links with standard code blocks

---

new_contributors/how-to-guide-template.md
new_contributors/software-review-template.md
new_contributors/tutorial-template.md

copying over files into new contributors folder for easy access

copied templates into new contributors folder for easy access

---

articles/android-custom-views-extending-view-subclass/index.md

adding front matter to subclass article

---

new_contributors/how-to-guide-template.md
new_contributors/software-review-template.md
new_contributors/tutorial-template.md

Improved templates as outlined in #595. Each template now has a link to an example article and is expanded with handy tips for new contributors.

Improved Templates

---

articles/dive-into-batch-scripting-language/index.md
authors/ahmad-mardeni/index.md
authors/aransiola-ayodele/index.md

minor edits to author pages-fixes

---

articles/react-native-agora-livestreaming-app/index.md

**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process and style-once published, you can then submit any number of articles.)**

React Native Agora Livestream Update

---

authors/mohan-raj/index.md

**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process and style-once published, you can then submit any number of articles.)**

Add Mohan Raj Author Info

---

articles/constructors-destructors/index.md

minor and spacing

---

articles/agora-express-token-server/index.md
articles/react-native-agora-livestreaming-app/index.md
articles/react-native-agora-video-conference-app/index.md

Hey @hectorkambow, I've added some links to my articles linking one another. Please review it.

[UPDATE] Agora Article Links

---

peer_reviewers/front-matter-process.md

front matter review process walkthrough

adding front matter review process walkthrough

---

authors/mohan-raj/index.md

@hectorkambow I've updated my author info. Can you please update it?

Update mohan-raj Author

---

articles/react-native-agora-video-conference-app/index.md
articles/react-native-razorpay/index.md

@hectorkambow seems like I messed up the Image links in the previous PR. I've fixed it in this PR 😅

Fix Image Links in React Native Articles

---

articles/javascript-particles-effect-with-tsparticles/index.md

**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process, quality, and style-once published, you can then submit any number of articles.)**
- [ x Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)

Updated tsParticles Article

---

articles/react-native-firebase-image-labeling/index.md
articles/react-native-firebase-landmark-recognition/index.md
articles/react-native-firebase-text-recognition/index.md

@hectorkambow I've updated the titles for 3 of my articles. I realized the old titles were too long and it could potentially hurt SEO.
- [Text Recognition using Firebase ML in a Non-Expo React Native Application](https://www.section.io/engineering-education/react-native-firebase-landmark-recognition/)
- [Image Labeling using Firebase ML in a Non-Expo React Native Application](https://www.section.io/engineering-education/react-native-firebase-image-labeling/)
- [Landmark Recognition Using Firebase ML in a Non-Expo React Native Application](https://www.section.io/engineering-education/react-native-firebase-landmark-recognition/)

Update React Native Firebase ML Article Titles

---

articles/introduction-to-grails-development-with-Intellij/index.md

Fixing this grails

---

articles/npm-vs-yarn-which-one-to-choose/index.md

Fixed article typo and broken image link in Choosing Between NPM and Yarn article.
Topic Suggestion: #1012.
Merged PR: #1580.

[Article Update] Choosing Between NPM and Yarn - Typo Fixes

---

authors/solomon-eseme/index.md

I noticed a minor error in my username.

Minor username error

---

articles/binary-tree-data-structure-python/index.md

This PR is to make a small change to a technical error in the [Binary Tree article](https://www.section.io/engineering-education/binary-tree-data-structure-python/)

[PATCH] Binary Tree Data Structure in Python

---

articles/activation-functions/index.md
articles/data-classes-in-python/index.md
articles/data-science-setup/index.md
articles/grid-search/index.md
articles/huffman-coding-in-python/index.md
articles/introduction-to-kotlin-coroutines/index.md
articles/introduction-to-kotlin-flows/index.md
articles/introduction-to-numpy/index.md
articles/python-boto3-and-amazon-dynamodb-programming-tutorial/index.md
articles/python-frameworks/index.md
articles/python-generators/index.md
articles/python-package-pypi/index.md
articles/python-projects-for-beginners/index.md
articles/python-static-typing/index.md
articles/random-number-genrator-python/index.md
articles/seaborn-tutorial/index.md
articles/setting-up-cicd-for-python-packages-using-github-actions/index.md
articles/sgd-classifier/index.md
articles/spring-boot-smtp/index.md
articles/steganography-in-python/index.md
articles/tuples-data-structure-python/index.md
articles/word-cloud/index.md
articles/working-with-pythons-unittest/index.md

adding the lang topic on some Python articles

adding topics to python articles

---

peer_reviewers/list-of-software-peer-reviewers.md

Creating a table (list) of all the current Peer Reviewer - with Author page - and GitHub profile.
This will also allow us to list out PR areas or expertise - and allow the EngEd community at large to get to know the PRs better.
This will be built upon and expanded.
adding a list of pr md file

adding a list of pr md file

---

peer_reviewers/list-of-software-peer-reviewers.md

Minor PR to modify areas of expertise in author page

Add areas of expertise

---

peer_reviewers/list-of-software-peer-reviewers.md

Areas of Expertise

---

authors/saiharsha-balasubramaniam/index.md

Minor PR to update my author bio

Update Author Page

---

authors/terrence-aluda/index.md

Fixes to my author page

---

new_contributors/developer-tool-box

adding dev tool box

---

assets/js/search.js

testing updates to sajari search logic

testing changes to sajari

---

assets/js/search.js

Reverts section-engineering-education/engineering-education#2294

Revert "testing changes to sajari"

---

content/authors/adhinga-fredrick/index.md

fixing author name
taking out accent mark - rendering issues

taking off tilde-author-rendering issue

---

layouts/partials/components/header.html
layouts/partials/engineering-education/articles-header.html

For first-time contributors and for more details, **see …

added conditionals to 'All' tag and header nav for local rendering

---

content/articles/Why-julia-is-slowly-replacing-python-for-machine-learning-and-data-science/index.md
content/articles/an-introduction-to-machine-learning-using-c++/index.md
content/articles/data-leakage/index.md
content/articles/differences-between-artificial-intelligence-machine-learning-and-deep-learning/index.md
content/articles/edge-tf-lite/index.md
content/articles/ensemble-learning/index.md
content/articles/handling-bias-in-machine-learning/index.md
content/articles/house-price-prediction/index.md
content/articles/imbalanced-data-in-ml/index.md
content/articles/introduction-to-random-forest-in-machine-learning/index.md
content/articles/mathematics-for-machine-learning/index.md
content/articles/reproducibility-machine-learning/index.md
content/articles/sustainable-ai-with-tinyml/index.md
content/articles/underspecification-machine-learning/index.md
content/articles/why-python-is-good-for-machine-learning/index.md

adding topics first 3 pages of ML

adding topics first 3 pages of ML

---

content/articles/ensemble-bias-var/index.md

I think this should fix the article links

fixing missing article links

---

content/articles/working-with-translate-api-in-nodejs/index.md

Fixing peer reviewer line for #2402

Fixing peer reviewer line

---

content/authors/saiharsha-balasubramaniam/index.md

adding index file back -not sure how it was deleted

re-adding index file

---

content/articles/how-sweet-is-kubernetes/index.md

Fixing author name

---

content-moderators/cheat-sheet.md
content-moderators/content-moderators.md
content-moderators/final-front-matter-review.md
content-moderators/how-to-preview-hugo.md

Have made some additions/improvements to the Content Moderator docs to add extra information and clarify formatting.

Update Content Moderators Docs

---

content/articles/a-beginners-guide-on-how-to-become-a-blockchain-developer/index.md

Time & Topic for #2571

---

content/articles/creating-responsive-layouts-with-materialui-in-reactjs/index.md

This fixes #2463.  
For first-time contributors and for …

Creating Responsive Layouts with MaterialUI in react.js

---

content/articles/pure-mlp-architecture-for-computer-vision/index.md

fixing link

---

content/articles/desktop-application-with-react/index.md

For first-time contributors and for more details, **see …

Fix typo in article

---

content/articles/understanding-polymorphism-abstract-classes-using-c-/index.md

For first-time contributors and for more details, **see …

Updating my PR title (Understanding Polymorphism using Abstract Classes in C#)

---

content/authors/kevin-kimani/index.md

Fix the author type in `kevin-kimani`'s details. 
His details were not showing on his author page.

Author details fix

---

content/articles/blockchain-as-a-database/index.md
content/articles/blockchain-consensus-protocols/index.md
content/articles/cryptocurrency-tracking-telegram-bot/index.md
content/articles/history-of-blockchain/index.md
content/articles/how-crypto-mining-works/index.md
content/articles/how-to-build-your-own-private-blockchain/index.md
content/articles/secret-key-cryptography-in-js/index.md

Blockchain articles were added to the category.

Blockchain articles 

---

content/articles/docker-push-for-publishing-images-to-docker-hub/index.md

- fix the date in the latest article front matter

front matter fix

---

content/articles/running-a-multi-container-springboot-postgresql-application-with-docker-compose/index.md

- fix the images in article #3021

Images not loading

---

content/articles/running-a-multi-container-springboot-postgresql-application-with-docker-compose/index.md

Images not showing

---

content-moderators/content-moderator.md

adding main PDF doc in the content moderator folder

adding main content moderator doc

---

peer_reviewers/list-of-software-peer-reviewers.md

@hectorkambow  
I've added my peer reviewer details.

Added peer reviewer details

---

content/articles/python-decorators/index.md
content/authors/mia-roberts/index.md

For first-time contributors and for more details, **see …

Getting started with decorators in python

---

content/articles/difference-between-kotlin-and-java/index.md
content/authors/nehemiah-maina/index.md

fixing author file
and adding author to front matter of article. 
cc @LinusMuema 
This article was missing the author - FYI - lets keep a closer eye on that 👍

adding author to front matter

---

.github/pull_request_template.md

Have updated the PR Template by improving the formatting and adding new points to the checklist.
- **Added new Pre-Submission Checks heading** - for pre-submission advice and notes
- **Reformatted notes as blockquotes** - because the previous template used a lot of bold styling which made the PR difficult to read
- **Highlighted that notes in blockquotes should be deleted** - prior to PR submission (to aid readability for peer reviewers)
- **Removed text about adding an additional comment to link issues to PRs** =  as that does not reliably work.
- **Moved the Link Topic to PR section** - to the endfor readability and made it a section
- **Clarified some terminology around issues/PRs** - vs topic suggestions/in-review articles
- **Added items to the checklist** - around technical code …

Updated Pull Request Template

---

content/articles/maps-api-in-a-webpage/index.md

Fixed date for *Using Maps, Places, and Directions APIs* article

Fixed date

---

content/authors/louise-findlay/index.md

Updated the bio text and changed links of my author page. Have previewed it and it looks correct.

Updated Louise Findlay Bio

---

content/articles/image-compression-using-PCA/index.md

changing folder names - lower case

---

content/_index.md

adding redirect for discord article

adding redirect

---

content/articles/building-simple-maps-using-leaflet-js/index.md
content/authors/femi-ige-muyiwa-oladele/index.md

author fix

---

content/articles/building-simple-maps-using-leaflet-js/index.md

fixed img url

---

layouts/partials/components/footer.html
layouts/partials/components/header.html

Removed CTAs from header, including:
- Contact
- Login
- Get Started
... also removed Contact button from footer

removed ctas from header

---

layouts/partials/components/footer.html
layouts/partials/components/header.html
layouts/partials/footer-scripts.html

- added white paper banner via Sumo script in footer
- removed commented out code from header/footer

added white paper banner, removed commented out code

---

content/articles/core-concepts-of-redux-store-management/index.md

fixed image urls

---

content/articles/watch-dark-mode-js-css/index.md
content/authors/magdaline-kariuki/index.md

@geoffrey45 - Please be sure to enter the correct author name in your front matter. I have fixed this one for you.
cc @Njerikariuki

Fixed author details for #3609

---

content/articles/laravel-sanctum-api-auth/index.md

Fixing migration

---

content/articles/searching-and-sorting-techniques/index.md

brand new front matter added

---

content/articles/searching-and-sorting-techniques/index.md

Reverts section-engineering-education/engineering-education#4076

Revert "Searching and sorting techniques"

---

peer_reviewers/list-of-software-peer-reviewers.md

@ahmadmardeni1 I added my areas of expertise. Can you review this and merge it, please?

Added Myself to Developer List

---

content/articles/flutter-social-authentication/index.md

article update

---

content/articles/an-all-in-one-spring-security-crash-course-for-java-developers/index.md

Update existing article on spring security, fixing an error in the code, and updating the explanations to account for it.

Update My Article On Spring Security

---

.github/ISSUE_TEMPLATE/pull-request-template.md
new_contributors/FAQ.md

testing template
No template on this screen (in the process of opening) PR

adding paypal note

---

new_contributors/CONTRIBUTING.md

deleting old template links

---

new_contributors/FAQ.md

adding to FAQ

---

content-moderators/plagiarism-check-document.md

- updated the plagiarism check cheat sheet

Cheat sheet

---

layouts/_default/baseof.html

Remove collapsible footer.
https://section.tpondemand.com/entity/16191-remove-collapsible-footer

Remove Collapsible footer.

---

layouts/articles/single.html

Fix ID configuration for Hyvor Comments.

Fix Hyvor ID config.

---

assets/scss/components/_all.scss
assets/scss/components/_engEd-banner.scss
layouts/articles/single.html
layouts/partials/engineering-education/eng-ed-banner.html

- Add EngEd banner to top of EngEd articles.
- Remove EngEd/Author CTA's at the bottom of articles (will be replace with Author Sidebar including CTA's).

Enged article banner

---

content/articles/understanding-cross-site-scripting-attacks/index.md

fixed image paths for #5170

---

content/articles/accelerating-automation-with-hyper-automation/index.md

- fixed the hero image in #5230

Hero image fix

---

content/articles/object-detection-with-yolov5-and-pytorch/index.md
content/articles/understanding-search-algorithms-in-ai/index.md

Fixed hero image URLs for two articles that were not rendering hero images properly.

Fixed hero images for two articles

---

content/articles/how-to-classify-ecg-signal-using-continuous-wavelet-transform-and-alexnet/index.md

Removed special character from the introduction paragraph.

Minor fix 

---

layouts/articles/single.html

Fix sidebar img url.

---

layouts/articles/single.html

After discussing we've decided to remove the school field from the author sidebar. Will likely re-implement in the future.

Remove school field from article sidebar.

---

.github/config.yml

Automate welcome messages to first time contributors first PR.

Automate welcome message to first time contributors first PR.

---

content-moderators/plagiarism-check-document.md
content/articles/how-to-build-a-currency-converter-with-react-and-its-material-ui/index.md

Fixed Typo

---

content/authors/cosmas-morwabe/index.md

This pull request updates my author file.

Update author file

---

layouts/partials/footer-scripts.html

Improvements to LCP by removing AddThis script from GTM and adding to footer of article pages.

Place addthis script in footer conditionally for article pages.

---

content/articles/overview-of-rootkits/index.md

Overview of Rootkits

---

.github/customizable-comments.yml

Add customizable-comments.yml to test jobot params.

Test jobot params.

---

content/articles/implementing-aes-encryption-and-decryption-in-java/index.md

Fix hero image for Implementing AES Encryption And Decryption In Java article.

Fixed hero image

---

content/authors/briana-nzivu/index.md

Fixing author info

---

content/articles/jetpack-compose-forms/index.md

Made some minor changes in grammar and readability of the first Jetpack Compose form builder article.

Grammar changes

---

layouts/partials/components/header.html

Update logo in site header to be clickable on the EngEd homepage

updated logo to make clickable on EngEd home

---

content/authors/geoffrey-mungai/index.md

This pull request updates my author bio and  adds a list of skills.

[Author] Add author skills

---

.github/ISSUE_TEMPLATE/enged-content-idea-suggestion.md

Issue template grammar fix

---

content/authors/louise-findlay/index.md
layouts/authors/rss.xml

Testing adding the author feed for my author profile to try and replicate and fix the issue causing it to be reverted previously.
Related to #7105 & #7273 & #7106.

Testing Author Feeds

---

layouts/authors/single.html

Pushing fix for regex url on production.

Fix regex for prod url.

---

README.md
new_contributors/CONTRIBUTING.md
new_contributors/FAQ.md
new_contributors/README.md
new_contributors/getting-started.md

MAJOR re-haul to EngEd docs

---

.github/ISSUE_TEMPLATE/kubernetes-edge-app-hackathon-registration.md

This will serve as our registration form for the EngEd 2022 hackathon. 
That way students can attach PR submissions and we have a way to track who is registering.

Kubernetes Edge App Hackathon Registration

---

content/authors/eric-kahuha/index.md

Author bio update

---

README.md

Minor refinement to the CCC (community contribution) paragraphs in the readme

refining CCC portion of the docs.

---

content/authors/willies-ogola/index.md

Added skills section

---

new_contributors/UPLOAD_INSTRUCTIONS.md
new_contributors/enged-author-profile-guidelines.md

Will attach to onboarding email

splitting up author profile creation

---

.github/workflows/comment-topics.yml

Testing the Comment Topic Links Feature Request GitHub action file.
This closes #7532.

Testing Comment Topic Links Feature Request

---

content/authors/victor-kamau/index.md
content/authors/vincent-kimanzi/index.md

adding skills section (vincent)

---

data/testimonialsData.yml

updating testimonial on authors request

updating testimonial - Ahmad

---

Jenkinsfile.kei.beta
Makefile
ci/deploy-local.sh
ci/docker-update-build-push.sh
ci/kei-build-push.sh
k8s/base/deployment.yml
k8s/beta/deployment.yml
k8s/beta/kustomization.yml
k8s/beta/service.yml

Add Deployment, service and config for beta environments.

Add beta config

---

content/articles/implementing-a-spring-query-language-spring-boot-search-operations/index.md
content/articles/web3js-vs-ethersjs/index.md

date
url name change to match file name
> If you have not already, please go over our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for more tips and …

made some minor edits

---

data/testimonialsData.yml

femi & shuaib
Adding two new student testimonials to testimonial section

adding two new testimonials

---

Jenkinsfile.kei

Add step to Jenkinsfile to trigger the `purge-enged-varnish-cache` job.

add step to trigger purge-enged-varnish-cache.

---

content/authors/samuel-mwangi/index.md

EngEd Author Profile Update - Skills Section

---

layouts/authors/single.html

This PR calculates the sum of the authors total article page views and displays it on the insights section of the author profile page.
Navigate to beta.section.io and view a few different Author profiles. You should see the sum of all page views on the author insights section. Screenshot for reference:

Add total number of page views.

---

content/articles/forecasting-time-series-data-in-matlab/index.md

fixing ALL the image paths

---

content/articles/a-beginner-guide-to-softmax-regression-using-tensorflow/index.md
content/articles/growth-model-in-python/index.md

fixing image paths

---

data/testimonialsData.yml

adding 3 new tesimonials

---

new_contributors/README.md

adding some details to be able to share this doc on linkedin

adding some details

---

content/authors/peter-kayere/index.md
data/testimonialsData.yml

changing order
fixing an author image

adding more testimonials

---

content/authors/eric-gacoki/index.md

Update Author Profile

---

content/authors/adhinga-fredrick/index.md

@FREDERICO23 Adding a missing comma here to fix broken syntax in your frontmatter.

Fix authors profile syntax.

---

data/testimonialsData.yml

created a pr w/ 3 new testimonials
was NOT able to render - error via terminal

adding new testimonials

---

Jenkinsfile.kei
config/_default/config.toml
layouts/authors/single.html
layouts/partials/engineering-education/trending-articles.html
new_contributors/UPLOAD_INSTRUCTIONS.md

- Put `getJSON` request within a `with` block to handle errors. 
- Add `ignoreErrors = ["error-remote-getjson"]` to `/config/_default/config.toml`. 
- Add automatic builds once a day in the `Jenkinsfile.kei`.
cc - @hectorkambow

Handle getJSON errors. Disable getJSON build error.

---

content-moderators/creating-slack-subchannel.md
new_contributors/CONTRIBUTING.md
new_contributors/contributing-technical-content.md
new_contributors/enged-author-profile-guidelines.md

adding badge info
made some edits to other docs

adding sub channel info

---

assets/js/app.js

- Adds autoscroll to Testimonials slider
- Randomizes the order of testimonials on refresh.
**How to Test:**
The feature is currently deployed on beta.section.io/engineering-education/. Ensure that it auto scrolls after 9 seconds and that it randomizes the testimonials order on page refresh.

Testimonials enhancements

---

layouts/partials/engineering-education/trending-articles.html

Fix url for All Time Leaderboard.
cc @hectorkambow

Fix author link in All Time leaderboard.

---

content/authors/collince-okeyo/index.md

adding link to featured works section

adding robotics video to featured works

---

content/articles/building-a-payroll-system-with-nextjs/index.md
content/authors/eli-musa/index.md

fixing missing author
added skill section

fixing missing author

---

content/articles/building-a-payroll-system-with-nextjs/index.md

test-fixing year

---

layouts/partials/components/footer.html
layouts/partials/components/header.html

Update header footer

---

layouts/partials/components/header.html
layouts/partials/engineering-education/articles-header.html

Sm2000 patch 1

---

content/articles/building-a-video-streaming-app-with-spring/index.md

Article update for my guide on building a video player application with Spring Boot.

Video streaming article update

---

assets/scss/components/_engineering-education.scss

Update author sidebar style. This updates PR #7801.

Update author sidebar style

---

assets/scss/components/_hero-color.scss
layouts/partials/engineering-education/articles-header.html

Update messaging and styling for the home page banner.

Update home page banner

---

layouts/articles/single.html
layouts/partials/engineering-education/articles-header.html
layouts/partials/engineering-education/eng-ed-banner.html

supercloud tweaks

---

content/articles/setting-up-solar-windows-database-analyzer-for-monitoring-microsoft-sql-server/index.md

solarwinds updates
